### ISSUE TITLE
Initialize Admin User Interface

### ISSUE THREAD

**Issue by ghost** [Law3andakDam/website#1]
I will initialize all HTML files for admin section

**Comment by alexseif** [comment]
This should not be available until there's a code repository to work on.
If you are making simple HTML without any templat-ing than please initialise a separate repo named "admin-html" and then create elaborate tasks. 
For example 
- "Admin Default layout"
- "Admin CMS CRUD"
- "Admin Dashboard"

If it's not just simple HTML..
Than please initialise "website" repo and then proceed with the tasks as explained above.
